spring.application.name=bancodigital
spring.datasource.url=jdbc:postgresql://localhost:5432/nomedobanco
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=134679
spring.datasource.enabled=true
